language: python

cache:
  directories:
    - $HOME/xorca_test_data

notifications:
  email: false

matrix:
  include:
    - os: linux
      env: PY_VERSION=3 MINICONDA_NAME=Miniconda3-latest-Linux-x86_64.sh
    - os: osx
      language: generic
      env: PY_VERSION=3 MINICONDA_NAME=Miniconda3-latest-MacOSX-x86_64.sh

install:
    - wget http://repo.continuum.io/miniconda/${MINICONDA_NAME} -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda env create --name py3_xorca --file environment.yml
    - source activate py3_xorca
    - pip install -e .
    - git lfs install
    - du -sh $HOME/xorca_test_data || echo "didn't find test data"
    - git clone https://github.com/willirath/xorca_test_data.git $HOME/xorca_test_data
    - du -sh $HOME/xorca_test_data || echo "didn't find test data

script:
    - pytest -v --cov=xorca --cov-config=".coveragerc" --cov-report="term-missing" xorca/tests/
    - flake8 --extend-ignore=F841 xorca/

after_success:
    - codecov
