name: py3_xorca
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  - coverage
  - dask
  - flake8
  - git-lfs
  - matplotlib
  - memory_profiler
  - netCDF4
  - numpy
  - pandas
  - pytest<3
  - pytest-cov
  - seawater
  - xarray
  - pip:
      - codecov
      - git+https://github.com/xgcm/xgcm.git@bf4a2239d64dfd1c0d5b1af03e7394488433c11a
